version: 2
jobs:
  build:
    macos:
      xcode: "10.2.1"
    steps:
      - checkout
      - run:
          name: Install xcnew
          command: |
            brew tap manicmaniac/tap
            brew install xcnew
      - run:
          name: Create Xcode project
          command: |
            perl -pi -e 's/(?<=IPHONEOS_DEPLOYMENT_TARGET = )[0-9.]+/11.0/g' Example/Example.xcodeproj/project.pbxproj
            perl -pi -e 's/(?<=CODE_SIGN_STYLE = )Automatic/Manual/g' Example/Example.xcodeproj/project.pbxproj
            curl -o Example/.gitignore https://raw.githubusercontent.com/github/gitignore/master/Swift.gitignore
            git init Example
            git add .
      - store_artifacts:
          path: Example
