version: 2
jobs:
  build:
    macos:
      xcode: "10.2.1"
    environment:
      HOMEBREW_NO_AUTO_UPDATE: 1
    steps:
      - checkout
      - restore_cache:
          key: homebrew-v1-
      - run:
          name: Install xcnew
          command: |
            brew tap manicmaniac/tap
            brew install xcnew
            brew cleanup
      - save_cache:
          key: homebrew-v1-{{ epoch }}
          paths:
            - /usr/local/Homebrew
      - run:
          name: Create Xcode project
          command: |
            xcnew -n Organization -i com.example -t Example Example
            perl -pi -e 's/(?<=IPHONEOS_DEPLOYMENT_TARGET = )[0-9.]+/11.0/g' Example/Example.xcodeproj/project.pbxproj
            perl -pi -e 's/(?<=CODE_SIGN_STYLE = )Automatic/Manual/g' Example/Example.xcodeproj/project.pbxproj
            curl -o Example/.gitignore https://raw.githubusercontent.com/github/gitignore/master/Swift.gitignore
            git init Example
            git add .
      - run:
          name: Archive Xcode project
          command: |
            tar zcvf Example.tar.gz Example
      - store_artifacts:
          path: Example.tar.gz
