version: 2
jobs:
  build:
    macos:
      xcode: "10.2.1"
    environment:
      HOMEBREW_NO_AUTO_UPDATE: 1
    steps:
      - checkout
      - run:
          name: Install xcnew
          command: |
            brew install manicmaniac/tap/xcnew
      - run:
          name: Create Xcode project
          command: |
            xcnew -n Organization -i com.example -t Example Example
            find Example -type f -name '*.swift' -exec sed -i '' 's/Distiller/John Doe/g' {} \;
            perl -pi -e 's/(?<=IPHONEOS_DEPLOYMENT_TARGET = )[0-9.]+/11.0/g' Example/Example.xcodeproj/project.pbxproj
            perl -pi -e 's/(?<=CODE_SIGN_STYLE = )Automatic/Manual/g' Example/Example.xcodeproj/project.pbxproj
            curl -Lso Example/.gitignore https://raw.githubusercontent.com/github/gitignore/master/Swift.gitignore
            git init Example
            cd Example && git add .
      - run:
          name: Archive Xcode project
          command: |
            tar zcvf Example.tar.gz Example
      - store_artifacts:
          path: Example.tar.gz
